### PR TITLE
151 Carousel Slider Styling/Updates

### PR DESCRIPTION
**Pull request by mafromist**
Images on the slider have changed.
A gray overlay added on the bg-images.
Text area added on bg-images. (I've added as optional, if you don't like it or would like to change, feel free to do anything there)
List area styling has slightly changed to keep consistent.

### CODE REVIEW

**Comment by vcory** [comment]
No no...I just thought that is what you originally wanted!
All good. I really like what you have done! 👍

**Comment by mafromist** [comment]
Oh okay, if the flyers are not related to the written offer sure it cannot work.

Let's make a big title and write the offers under it. You don't need to keep the carousel.

**Comment by vcory** [comment]
I like the carousel! I really do.
No the flyers are related to the offers. There are 4 flyers I added to the assets.

**Comment by vcory** [comment]
Hmm interesting. I'll have a think and try something.
Appreciate the ideas. Thank you.

**Pull request merged**
